defaults:
  - base_pefm

env:
  env_class: close
  args:
    max_episode_length: 100
    ac_noise: 0.0
    vis: false
    freq: 5
    cam_resolution: 256

model:
  symmetry:
    group_type: so2
    distribution_type: projected_normal
    num_samples: 8
    entropy_weight: 0.01
