defaults:
  - base_pefm

env:
  env_class: compass_close
  args:
    max_episode_length: 120

model:
  symmetry:
    group_type: so2
    distribution_type: projected_normal
    num_samples: 8
    entropy_weight: 0.01
