defaults:
  - base_pefm

env:
  env_class: insert
  args:
    max_episode_length: 80
    cam_resolution: 256
    vis: false
    freq: 5
    ac_noise: 0.0

model:
  symmetry:
    group_type: c4
    distribution_type: gumbel_categorical
    num_samples: 4
    entropy_weight: 0.005
